# Generated by Django 6.0.3 on 2026-03-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fuzzy_score', models.FloatField()),
                ('ml_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
