# Generated by Django 6.0.3 on 2026-03-15 21:32

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_beneficiary_deathverification_assetbeneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
